name: Run Playwright tests and deploy Allure report

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          curl -O -L https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.zip
          unzip -q allure-commandline-2.13.8.zip -d /opt/
          echo "/opt/allure-2.13.8/bin" >> $GITHUB_PATH

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        if: always()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'arke@nnit.com'
          git add allure-report
          git commit -m 'Deploy Allure report'
          git checkout gh-pages || git checkout --orphan gh-pages
          git push origin HEAD:gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}